### ISSUE TITLE
Checklist management

### ISSUE THREAD

**Issue by Perdolique** [Perdolique/perd#57]
- [ ] The user can find items in its inventory on the checklist page.
- [ ] User can add an item to the checklist.
- [ ] User can delete an item from the checklist.
- [ ] User can see items on the checklist.
